### ISSUE TITLE
Improve loading performance

### ISSUE THREAD

**Issue by sishu7** [lgarron/pet-the-kitties#5]
There may be a bug in pre-loading, or we may need more aggressive pre-loading (and maybe some sort of native solution on iOS).

**Comment by lgarron** [comment]
Prefetching was improved in 09871e1b3947421589d46a2aab3f3fe6bc75e864.
We may want to consider prefetching more cats, but prefetching `gif` and `jpg` for the next cat (properly) is already much better than before.
